/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-06-03 16:22:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Workspaces/apache-tomcat-8.0.35/wtpwebapps/authclient/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.2.2.RELEASE.jar", Long.valueOf(1464278509467L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1458328493732L));
    _jspx_dependants.put("jar:file:/C:/Workspaces/apache-tomcat-8.0.35/wtpwebapps/authclient/WEB-INF/lib/spring-webmvc-4.2.2.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1444904064000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      if (_jspx_meth_spring_005feval_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f3(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f4(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f5(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f6(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f7(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Outlook Autentication</title>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_spring_005furl_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_spring_005furl_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bootstrapCss}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${coreCss}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      if (_jspx_meth_spring_005furl_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jqueryJs}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"#\">Spring Outlook Authentication</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" style=\"min-height: 500px\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"starter-template\">\r\n");
      out.write("\t\t<h1>Search Form</h1>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"feedback\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<form class=\"form-horizontal\" id=\"search-form\">\r\n");
      out.write("\t\t\t<div class=\"form-group form-group-lg\">\r\n");
      out.write("\t\t\t\t<label class=\"col-sm-2 control-label\">Username</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t<input type=text class=\"form-control\" id=\"username\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group form-group-lg\">\r\n");
      out.write("\t\t\t\t<label class=\"col-sm-2 control-label\">Email</label>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"email\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" id=\"bth-search\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-primary btn-lg\">Simple Login</button>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"bth-outlook\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-primary btn-lg\">Outlook Logging</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" id=\"bth-send-email\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-primary btn-lg\" style=\"display:none\">Enviar Email</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<div class=\"form-group form-group-lg\" style=\"display:none\">\r\n");
      out.write("\t\t\t<label class=\"col-sm-2 control-label\">Authorization Code</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"code_id\"></input>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group form-group-lg\" style=\"display:none\">\r\n");
      out.write("\t\t\t<label class=\"col-sm-2 control-label\">Session State</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"session_state_id\"></input>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group form-group-lg\" style=\"display:none\">\r\n");
      out.write("\t\t\t<label class=\"col-sm-2 control-label\">Access Token</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"acc_token_id\"></input>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group form-group-lg\" style=\"display: none;\">\r\n");
      out.write("\t\t\t<label class=\"col-sm-2 control-label\">Token Type</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"acc_token_type\"></input>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group form-group-lg\" style=\"display: none;\">\r\n");
      out.write("\t\t\t<label class=\"col-sm-2 control-label\">Authentication Token</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"auth_token_id\"></input>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"form-group form-group-lg\" style=\"display: none;\">\r\n");
      out.write("\t\t\t<label class=\"col-sm-2 control-label\">Refresh Token</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"refresh_token_id\"></input>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"form-group form-group-lg\">\r\n");
      out.write("\t\t\t<label class=\"col-sm-2 control-label\">Nombre</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"nombre_id\"></input>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"form-group form-group-lg\">\r\n");
      out.write("\t\t\t<label class=\"col-sm-2 control-label\">Apellido</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"apellido_id\"></input>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"form-group form-group-lg\">\r\n");
      out.write("\t\t\t<label class=\"col-sm-2 control-label\">IP Address</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"ipaddr_id\"></input>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"form-group form-group-lg\">\r\n");
      out.write("\t\t\t<label class=\"col-sm-2 control-label\">Correo</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"correo_id\"></input>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group form-group-lg\" style=\"display: none;\">\r\n");
      out.write("\t\t\t<label class=\"col-sm-2 control-label\">Asunto</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"subject_email\"></input>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"form-group form-group-lg\" style=\"display: none;\">\r\n");
      out.write("\t\t\t<label class=\"col-sm-2 control-label\">Mensaje</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"message_email\"></input>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar auth_code;\r\n");
      out.write("\tvar acc_token;\r\n");
      out.write("\tvar sess_state;\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getUrlBase() {\r\n");
      out.write("\t\treturn 'https://xinefserver.com:9090/outlook-auth/';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#search-form\").submit(function(event) {\r\n");
      out.write("\t\t\t// Disble the search button\r\n");
      out.write("\t\t\tenableSearchButton(false);\r\n");
      out.write("\t\t\t// Prevent the form from submitting via the browser.\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\tsearchViaAjax();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#bth-outlook\").click(function(data){\r\n");
      out.write("\t\t\tlogOutlook();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#bth-send-email\").click(function(data){\r\n");
      out.write("\t\t\tsendEmail();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar code = urlParameterExtraction.queryStringParameters['oid'];\r\n");
      out.write("\t\tgetUserDataByOid(code);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction setTokenID() {\r\n");
      out.write("\t\t$('#code_id').val(auth_code);\r\n");
      out.write("\t\t$('#token_id').val(acc_token);\r\n");
      out.write("\t\t$('#session_state_id').val(sess_state);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction logOutlook(){\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: getUrlBase() + '/redirectAuth',\r\n");
      out.write("\t\t\ttype: 'GET',\r\n");
      out.write("\t\t\tdatatype: 'jsonp',\r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\twindow.location.href = data;\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(\"FAIL\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tbeforeSend: function(req) {\r\n");
      out.write("\t\t\t\treq.setRequestHeader('Access-Control-Allow-Origin', '*');\r\n");
      out.write("\t\t\t\treq.setRequestHeader('Access-Control-Allow-Methods', 'GET, PUT, POST, DELETE, OPTIONS');\r\n");
      out.write("\t\t\t\treq.setRequestHeader('Access-Control-Allow-Headers', 'Accept, Content-Type, Content-Range, Content-Disposition, Content-Description');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getPositionSign(urlName) {\r\n");
      out.write("\t\tfor(i=0; i<urlName.length; ++i) {\r\n");
      out.write("\t\t\tif (urlName[i] == '?' || urlName[i] == '#') return i;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar urlParameterExtraction = new (function () { \r\n");
      out.write("\t\t  function splitQueryString(queryStringFormattedString) { \r\n");
      out.write("\t\t    var split = queryStringFormattedString.split('&'); \r\n");
      out.write("\t\t    // If there are no parameters in URL, do nothing.\r\n");
      out.write("\t\t    if (split == \"\") {\r\n");
      out.write("\t\t      return {};\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    var results = {}; \r\n");
      out.write("\t\t    // If there are parameters in URL, extract key/value pairs. \r\n");
      out.write("\t\t    for (var i = 0; i < split.length; ++i) { \r\n");
      out.write("\t\t      var p = split[i].split('=', 2); \r\n");
      out.write("\t\t      if (p.length == 1) \r\n");
      out.write("\t\t        results[p[0]] = \"\"; \r\n");
      out.write("\t\t      else \r\n");
      out.write("\t\t        results[p[0]] = decodeURIComponent(p[1].replace(/\\+/g, \" \")); \r\n");
      out.write("\t\t    } \r\n");
      out.write("\t\t    return results; \r\n");
      out.write("\t\t  } \r\n");
      out.write("\t\t  // Split the query string (after removing preceding '#'). \r\n");
      out.write("\t\t  var positionInterrogation = getPositionSign(window.location.href);\r\n");
      out.write("\t\t  this.queryStringParameters = splitQueryString(window.location.href.substr(positionInterrogation+ 1)); \r\n");
      out.write("\t\t})(); \r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tfunction searchViaAjax() {\r\n");
      out.write("\t\tvar search = {}\r\n");
      out.write("\t\tsearch[\"username\"] = $(\"#username\").val();\r\n");
      out.write("\t\tsearch[\"email\"] = $(\"#email\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${home}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("search/api/getSearchResult\",\r\n");
      out.write("\t\t\tdata : JSON.stringify(search),\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\ttimeout : 100000,\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(\"SUCCESS: \", data);\r\n");
      out.write("\t\t\t\tdisplay(data);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(\"ERROR: \", e);\r\n");
      out.write("\t\t\t\tdisplay(e);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdone : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(\"DONE\");\r\n");
      out.write("\t\t\t\tenableSearchButton(true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getTokensByAuthCode(authCode) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"https://login.microsoftonline.com/common/oauth2/v2.0/token\",\r\n");
      out.write("\t\t\tdatatype: \"json\",\r\n");
      out.write("\t\t\tcrossDomain: true,\r\n");
      out.write("\t\t\ttype: \"POST\",\t\r\n");
      out.write("\t\t\tcontentType: \"application/x-www-form-urlencoded\",\r\n");
      out.write("\t\t\txhrFields: {\r\n");
      out.write("\t\t\t    withCredentials: false\r\n");
      out.write("\t\t\t  },\r\n");
      out.write("\t\t\tdata: {\r\n");
      out.write("\t\t\t\t\"code\": authCode,\r\n");
      out.write("\t\t\t\t\"client_id\": '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clientID.codigo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("\t\t\t\t\"redirect_uri\": '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${redirect.codigo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("\t\t\t\t\"client_secret\": '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clientSec.codigo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("\t\t\t\t\"grant_type\": 'authorization_code',\r\n");
      out.write("\t\t\t\t\"cors\": {\r\n");
      out.write("\t\t\t        \"headers\": [\"Accept\", \"Authorization\", \"Content-Type\", \"If-None-Match\", \"Accept-language\"]\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t$(\"#acc_token_id\").val(data.access_token);\r\n");
      out.write("\t\t\t\t$(\"#auth_token_id\").val(data.id_token);\r\n");
      out.write("\t\t\t\t$(\"#refresh_token_id\").val(data.refresh_token);\r\n");
      out.write("\t\t\t\t$(\"#acc_token_type\").val(data.token_type);\r\n");
      out.write("\t\t\t\tgetUserDataByToken(data.access_token);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(\"FAIL\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tbeforeSend: function(req) {\r\n");
      out.write("\t\t\t\treq.setRequestHeader('Access-Control-Allow-Methods', 'GET, PUT, POST, DELETE, OPTIONS');\r\n");
      out.write("\t\t\t\treq.setRequestHeader('Access-Control-Allow-Headers', 'Accept, Content-Type, Content-Range, Content-Disposition, Content-Description');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getUserData(acc_token, acc_type) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"https://outlook.office.com/api/v2.0/me\",\r\n");
      out.write("\t\t\tdatatype: \"jsonp\",\r\n");
      out.write("\t\t\ttype: \"GET\",\t\r\n");
      out.write("\t\t\txhrFields: {\r\n");
      out.write("\t\t\t    withCredentials: false\r\n");
      out.write("\t\t\t  },\r\n");
      out.write("\t\t\theaders: {\r\n");
      out.write("\t\t\t\t\"access_token\": acc_token,\r\n");
      out.write("\t\t\t\t\"Authorization\": \"Bearer \" + acc_token,\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(\"DONE\");\r\n");
      out.write("\t\t\t\t$('#correo_id').val(data.EmailAddress);\r\n");
      out.write("\t\t\t\t$('#nombre_id').val(data.DisplayName);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(\"FAIL\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getUserDataByToken(acc_token) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: getUrlBase() + '/getBodyToken',\r\n");
      out.write("\t\t\ttype: 'POST',\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\tcache: false,\r\n");
      out.write("\t\t\tdatatype: 'json',\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tidToken: acc_token\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t$('#correo_id').val(data.unique_name);\r\n");
      out.write("\t\t\t\t$('#nombre_id').val(data.given_name);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(\"FAIL\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getUserDataByOid(oidToken) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: getUrlBase() + '/getSessionInfo',\r\n");
      out.write("\t\t\ttype: 'GET',\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\tcache: false,\r\n");
      out.write("\t\t\tdatatype: 'json',\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\toid: oidToken\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t$('#correo_id').val(data.unique_name);\r\n");
      out.write("\t\t\t\t$('#nombre_id').val(data.given_name);\r\n");
      out.write("\t\t\t\t$('#apellido_id').val(data.family_name);\r\n");
      out.write("\t\t\t\t$('#ipaddr_id').val(data.ipaddr);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(\"FAIL\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction sendEmail() {\r\n");
      out.write("\t\tacc_token = $(\"#acc_token_id\").val();\r\n");
      out.write("\t\tsubject_value = $(\"#subject_email\").val();\r\n");
      out.write("\t\tcontent_value = $(\"#message_email\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar Message = {\r\n");
      out.write("\t\t\t\t\"Message\": {\r\n");
      out.write("\t\t\t\t    \"Subject\": subject_value,\r\n");
      out.write("\t\t\t\t    \"Body\": {\r\n");
      out.write("\t\t\t\t      \"ContentType\": \"Text\",\r\n");
      out.write("\t\t\t\t      \"Content\": content_value,\r\n");
      out.write("\t\t\t\t    },\r\n");
      out.write("\t\t\t\t    \"ToRecipients\": [\r\n");
      out.write("\t\t\t\t      {\r\n");
      out.write("\t\t\t\t        \"EmailAddress\": {\r\n");
      out.write("\t\t\t\t          \"Address\": \"dmansilla07@gmail.com\"\r\n");
      out.write("\t\t\t\t        }\r\n");
      out.write("\t\t\t\t      }\r\n");
      out.write("\t\t\t\t    ]\r\n");
      out.write("\t\t\t\t  },\r\n");
      out.write("\t\t\t\t\"SaveToSentItems\": \"true\"\r\n");
      out.write("\t\t    };\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"https://outlook.office.com/api/v2.0/me/sendmail\",\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\tcontentType: \"application/json\",\r\n");
      out.write("\t\t\theaders: {\r\n");
      out.write("\t\t\t\t\"Authorization\": \"Bearer \" + acc_token,\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdata: JSON.stringify(Message),\r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(\"DONE\");\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(\"FAIL\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction enableSearchButton(flag) {\r\n");
      out.write("\t\t$(\"#btn-search\").prop(\"disabled\", flag);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction display(data) {\r\n");
      out.write("\t\tvar json = \"<h4>Ajax Response</h4><pre>\"\r\n");
      out.write("\t\t\t\t+ JSON.stringify(data, null, 4) + \"</pre>\";\r\n");
      out.write("\t\t$('#feedback').html(json);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005feval_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f0 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    _jspx_th_spring_005feval_005f0.setPageContext(_jspx_page_context);
    _jspx_th_spring_005feval_005f0.setParent(null);
    // /WEB-INF/views/jsp/welcome.jsp(7,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f0.setExpression("T(com.avantica.web.model.OutlookParameters).TOKEN_URL");
    // /WEB-INF/views/jsp/welcome.jsp(7,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f0.setVar("tokeUrl");
    int[] _jspx_push_body_count_spring_005feval_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005feval_005f0 = _jspx_th_spring_005feval_005f0.doStartTag();
      if (_jspx_th_spring_005feval_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005feval_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005feval_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005feval_005f0.doFinally();
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f1 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    _jspx_th_spring_005feval_005f1.setPageContext(_jspx_page_context);
    _jspx_th_spring_005feval_005f1.setParent(null);
    // /WEB-INF/views/jsp/welcome.jsp(8,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f1.setExpression("T(com.avantica.web.model.OutlookParameters).TOKEN_LOGIN");
    // /WEB-INF/views/jsp/welcome.jsp(8,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f1.setVar("tokenLogin");
    int[] _jspx_push_body_count_spring_005feval_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005feval_005f1 = _jspx_th_spring_005feval_005f1.doStartTag();
      if (_jspx_th_spring_005feval_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005feval_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005feval_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005feval_005f1.doFinally();
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f2 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    _jspx_th_spring_005feval_005f2.setPageContext(_jspx_page_context);
    _jspx_th_spring_005feval_005f2.setParent(null);
    // /WEB-INF/views/jsp/welcome.jsp(9,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f2.setExpression("T(com.avantica.web.model.OutlookParameters).CLIEND_ID");
    // /WEB-INF/views/jsp/welcome.jsp(9,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f2.setVar("clientID");
    int[] _jspx_push_body_count_spring_005feval_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005feval_005f2 = _jspx_th_spring_005feval_005f2.doStartTag();
      if (_jspx_th_spring_005feval_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005feval_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005feval_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005feval_005f2.doFinally();
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f3 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    _jspx_th_spring_005feval_005f3.setPageContext(_jspx_page_context);
    _jspx_th_spring_005feval_005f3.setParent(null);
    // /WEB-INF/views/jsp/welcome.jsp(10,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f3.setExpression("T(com.avantica.web.model.OutlookParameters).CLIEND_SEC");
    // /WEB-INF/views/jsp/welcome.jsp(10,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f3.setVar("clientSec");
    int[] _jspx_push_body_count_spring_005feval_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005feval_005f3 = _jspx_th_spring_005feval_005f3.doStartTag();
      if (_jspx_th_spring_005feval_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005feval_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005feval_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005feval_005f3.doFinally();
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f4 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    _jspx_th_spring_005feval_005f4.setPageContext(_jspx_page_context);
    _jspx_th_spring_005feval_005f4.setParent(null);
    // /WEB-INF/views/jsp/welcome.jsp(11,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f4.setExpression("T(com.avantica.web.model.OutlookParameters).AUTHORIZ");
    // /WEB-INF/views/jsp/welcome.jsp(11,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f4.setVar("authoriz");
    int[] _jspx_push_body_count_spring_005feval_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005feval_005f4 = _jspx_th_spring_005feval_005f4.doStartTag();
      if (_jspx_th_spring_005feval_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005feval_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005feval_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005feval_005f4.doFinally();
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f5 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    _jspx_th_spring_005feval_005f5.setPageContext(_jspx_page_context);
    _jspx_th_spring_005feval_005f5.setParent(null);
    // /WEB-INF/views/jsp/welcome.jsp(12,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f5.setExpression("T(com.avantica.web.model.OutlookParameters).SCOPE");
    // /WEB-INF/views/jsp/welcome.jsp(12,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f5.setVar("scope");
    int[] _jspx_push_body_count_spring_005feval_005f5 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005feval_005f5 = _jspx_th_spring_005feval_005f5.doStartTag();
      if (_jspx_th_spring_005feval_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005feval_005f5[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005feval_005f5.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005feval_005f5.doFinally();
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f6 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    _jspx_th_spring_005feval_005f6.setPageContext(_jspx_page_context);
    _jspx_th_spring_005feval_005f6.setParent(null);
    // /WEB-INF/views/jsp/welcome.jsp(13,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f6.setExpression("T(com.avantica.web.model.OutlookParameters).REDIRECT");
    // /WEB-INF/views/jsp/welcome.jsp(13,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f6.setVar("redirect");
    int[] _jspx_push_body_count_spring_005feval_005f6 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005feval_005f6 = _jspx_th_spring_005feval_005f6.doStartTag();
      if (_jspx_th_spring_005feval_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005feval_005f6[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005feval_005f6.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005feval_005f6.doFinally();
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f6);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f7 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    _jspx_th_spring_005feval_005f7.setPageContext(_jspx_page_context);
    _jspx_th_spring_005feval_005f7.setParent(null);
    // /WEB-INF/views/jsp/welcome.jsp(14,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f7.setExpression("T(com.avantica.web.model.OutlookParameters).RESPONSE_TYPE_CODE");
    // /WEB-INF/views/jsp/welcome.jsp(14,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f7.setVar("resposeCode");
    int[] _jspx_push_body_count_spring_005feval_005f7 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005feval_005f7 = _jspx_th_spring_005feval_005f7.doStartTag();
      if (_jspx_th_spring_005feval_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005feval_005f7[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005feval_005f7.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005feval_005f7.doFinally();
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f7);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f8 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    _jspx_th_spring_005feval_005f8.setPageContext(_jspx_page_context);
    _jspx_th_spring_005feval_005f8.setParent(null);
    // /WEB-INF/views/jsp/welcome.jsp(15,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f8.setExpression("T(com.avantica.web.model.OutlookParameters).RESPONSE_TYPE_TOKEN");
    // /WEB-INF/views/jsp/welcome.jsp(15,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005feval_005f8.setVar("resposeToken");
    int[] _jspx_push_body_count_spring_005feval_005f8 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005feval_005f8 = _jspx_th_spring_005feval_005f8.doStartTag();
      if (_jspx_th_spring_005feval_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005feval_005f8[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005feval_005f8.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005feval_005f8.doFinally();
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f8);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/jsp/welcome.jsp(19,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setVar("home");
    // /WEB-INF/views/jsp/welcome.jsp(19,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/");
    // /WEB-INF/views/jsp/welcome.jsp(19,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setScope("request");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f0 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_spring_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_spring_005furl_005f0.setParent(null);
    // /WEB-INF/views/jsp/welcome.jsp(21,0) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005furl_005f0.setValue("/resources/core/css/hello.css");
    // /WEB-INF/views/jsp/welcome.jsp(21,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005furl_005f0.setVar("coreCss");
    int[] _jspx_push_body_count_spring_005furl_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005furl_005f0 = _jspx_th_spring_005furl_005f0.doStartTag();
      if (_jspx_th_spring_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005furl_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005furl_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005furl_005f0.doFinally();
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f1 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_spring_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_spring_005furl_005f1.setParent(null);
    // /WEB-INF/views/jsp/welcome.jsp(22,0) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005furl_005f1.setValue("/resources/core/css/bootstrap.min.css");
    // /WEB-INF/views/jsp/welcome.jsp(22,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005furl_005f1.setVar("bootstrapCss");
    int[] _jspx_push_body_count_spring_005furl_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005furl_005f1 = _jspx_th_spring_005furl_005f1.doStartTag();
      if (_jspx_th_spring_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005furl_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005furl_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005furl_005f1.doFinally();
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f2 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    _jspx_th_spring_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_spring_005furl_005f2.setParent(null);
    // /WEB-INF/views/jsp/welcome.jsp(27,0) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005furl_005f2.setValue("/resources/core/js/jquery.1.10.2.min.js");
    // /WEB-INF/views/jsp/welcome.jsp(27,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005furl_005f2.setVar("jqueryJs");
    int[] _jspx_push_body_count_spring_005furl_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005furl_005f2 = _jspx_th_spring_005furl_005f2.doStartTag();
      if (_jspx_th_spring_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005furl_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005furl_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005furl_005f2.doFinally();
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f2);
    }
    return false;
  }
}
